[[constraint]]
  name = "github.com/codeskyblue/go-sh"
  version = "0.2.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.5"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.3.0"

[[constraint]]
  branch = "v3"
  name = "gopkg.in/yaml.v3"

[prune]
  go-tests = true
  unused-packages = true
